language: objective-c
osx_image: xcode8
script:
    - xcodebuild test -project STNetTaskQueueTest/STNetTaskQueueTest.xcodeproj -scheme STNetTaskQueueTest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
