language: objective-c
osx_image: xcode7.2
before_script:
    - brew update && brew upgrade xctool
script:
    - xctool test -project STNetTaskQueueTest/STNetTaskQueueTest.xcodeproj -scheme STNetTaskQueueTest -sdk iphonesimulator
