language: objective-c
before_script:
    - brew update && brew upgrade xctool
script:
    - xctool test -project STNetTaskQueueTest/STNetTaskQueueTest.xcodeproj -scheme STNetTaskQueueTest -sdk iphonesimulator
